set stage07_prmtop "../07_solvation_ion_validation/pVBTMA12_12Cl_015MNaCl_pilot.prmtop"
set stage07_inpcrd "../07_solvation_ion_validation/pVBTMA12_12Cl_015MNaCl_pilot.inpcrd"
set boxX 55.366399
set boxY 60.206530
set boxZ 61.625519
