
source ../stage10_common.conf
parmfile ../inputs/pVBTMA12_PFOA_assoc.prmtop
ambercoor ../inputs/pVBTMA12_PFOA_assoc.inpcrd
bincoordinates 04_prod_1ns/prod_04.coor
binvelocities 04_prod_1ns/prod_04.vel
extendedSystem 04_prod_1ns/prod_04.xsc
firsttimestep 2250000
seed 202609325
langevin on
langevinTemp 310.15
langevinPiston on
langevinPistonTarget 1.01325
langevinPistonPeriod 100.0
langevinPistonDecay 50.0
langevinPistonTemp 310.15
useGroupPressure yes
DCDfile 05_prod_1ns/prod_05.dcd
DCDfreq 1000
outputName 05_prod_1ns/prod_05
run 500000
