
source ../stage10_common.conf
parmfile ../inputs/pVBTMA12_PFOA_assoc.prmtop
ambercoor ../inputs/pVBTMA12_PFOA_assoc.inpcrd
bincoordinates 00_equil_npt_500ps/equil.coor
binvelocities 00_equil_npt_500ps/equil.vel
extendedSystem 00_equil_npt_500ps/equil.xsc
firsttimestep 250000
seed 202609361
langevin on
langevinTemp 310.15
langevinPiston on
langevinPistonTarget 1.01325
langevinPistonPeriod 100.0
langevinPistonDecay 50.0
langevinPistonTemp 310.15
useGroupPressure yes
DCDfile 01_prod_1ns/prod_01.dcd
DCDfreq 1000
outputName 01_prod_1ns/prod_01
run 500000
