source ../stage10_common.conf
parmfile ../inputs/pVBTMA12_PFOA_assoc.prmtop
ambercoor ../inputs/pVBTMA12_PFOA_assoc.inpcrd
bincoordinates 05_prod_1ns/prod_05.coor
binvelocities 05_prod_1ns/prod_05.vel
extendedSystem 05_prod_1ns/prod_05.xsc
firsttimestep 2750000
seed 202609366
langevin on
langevinTemp 310.15
langevinPiston on
langevinPistonTarget 1.01325
langevinPistonPeriod 100.0
langevinPistonDecay 50.0
langevinPistonTemp 310.15
useGroupPressure yes
DCDfile 06_prod_1ns/prod_06.dcd
DCDfreq 1000
outputName 06_prod_1ns/prod_06
run 500000
