# Resin-only chloride-form minimization
# No resin shape restraints are used.

amber             yes
parmfile          ../04_leap/solvated_resin_cl.prmtop
ambercoor         ../04_leap/solvated_resin_cl.inpcrd

outputname        resin_only_min
binaryoutput      yes

# AMBER-compatible nonbonded settings
exclude           scaled1-4
readexclusions    yes
1-4scaling        0.833333333
scnb              2.0

switching         off
cutoff            9.0
pairlistdist      11.0
LJcorrection      on

PME               yes
PMEGridSpacing    1.0

cellBasisVector1  104.00921700 0.0 0.0
cellBasisVector2  0.0 95.43854000 0.0
cellBasisVector3  0.0 0.0 77.68475100
cellOrigin        0.0 0.0 0.0

temperature       310.15

rigidBonds        all
rigidTolerance    1.0e-8
timestep          2.0

outputEnergies    100
outputTiming      100
restartfreq       1000
dcdfreq           1000
xstFreq           1000

minimize          10000
