# Resin-only chloride-form NVT heating
# No resin shape restraints are used.

amber             yes
parmfile          ../04_leap/solvated_resin_cl.prmtop
ambercoor         ../04_leap/solvated_resin_cl.inpcrd

binCoordinates    resin_only_min.restart.coor

outputname        resin_only_nvt_heat
binaryoutput      yes

exclude           scaled1-4
readexclusions    yes
1-4scaling        0.833333333
scnb              2.0

switching         off
cutoff            9.0
pairlistdist      11.0
LJcorrection      on

PME               yes
PMEGridSpacing    1.0

cellBasisVector1  104.00921700 0.0 0.0
cellBasisVector2  0.0 95.43854000 0.0
cellBasisVector3  0.0 0.0 77.68475100
cellOrigin        0.0 0.0 0.0

temperature       310.15

rigidBonds        all
rigidTolerance    1.0e-8
timestep          2.0

langevin          on
langevinTemp      310.15
langevinDamping   1.0

outputEnergies    500
outputTiming      500
restartfreq       2500
dcdfreq           2500
xstFreq           2500

# Gentle heating without restraints
reinitvels         50.0
run                25000

reinitvels         100.0
run                25000

reinitvels         150.0
run                25000

reinitvels         200.0
run                25000

reinitvels         250.0
run                25000

reinitvels         310.15
run                50000
