# Resin-only chloride-form short NPT equilibration
# No resin shape restraints are used.

amber             yes
parmfile          ../04_leap/solvated_resin_cl.prmtop
ambercoor         ../04_leap/solvated_resin_cl.inpcrd

binCoordinates    resin_only_nvt_heat.restart.coor
binVelocities     resin_only_nvt_heat.restart.vel
extendedSystem    resin_only_nvt_heat.restart.xsc

outputname        resin_only_npt_short
binaryoutput      yes

exclude           scaled1-4
readexclusions    yes
1-4scaling        0.833333333
scnb              2.0

switching         off
cutoff            9.0
pairlistdist      11.0
LJcorrection      on

PME               yes
PMEGridSpacing    1.0

rigidBonds        all
rigidTolerance    1.0e-8
timestep          2.0

langevin          on
langevinTemp      310.15
langevinDamping   1.0

langevinPiston              on
langevinPistonTarget        1.01325
langevinPistonPeriod        100.0
langevinPistonDecay         50.0
langevinPistonTemp          310.15

useGroupPressure  yes
useFlexibleCell   no
useConstantArea   no

outputEnergies    500
outputTiming      500
restartfreq       2500
dcdfreq           2500
xstFreq           2500

run               250000
