#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import parmed as pmd

AVOGADRO = 6.02214076e23
ANGSTROM3_TO_LITER = 1.0e-27


def cell_volume_ang3(box):
    if box is None or len(box) < 6:
        raise ValueError("Periodic box with lengths and angles is required")
    a, b, c, alpha, beta, gamma = [float(x) for x in box[:6]]
    ca = math.cos(math.radians(alpha))
    cb = math.cos(math.radians(beta))
    cg = math.cos(math.radians(gamma))
    factor = 1.0 + 2.0 * ca * cb * cg - ca * ca - cb * cb - cg * cg
    if factor <= 0.0:
        raise ValueError(f"Invalid unit-cell geometry: {box}")
    return a * b * c * math.sqrt(factor)


def nearest_integer(x):

    return int(math.floor(x + 0.5))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prmtop", default="pVBTMA12_solvated_noions.prmtop")
    ap.add_argument("--inpcrd", default="pVBTMA12_solvated_noions.inpcrd")
    ap.add_argument("--target-molar", type=float, default=0.150)
    ap.add_argument("--neutralizing-chloride", type=int, default=12)
    ap.add_argument("--json-out", default="salt_setup.json")
    ap.add_argument("--leap-out", default="build_chloride_pilot_salted.generated.leap")
    args = ap.parse_args()

    if args.target_molar <= 0.0:
        raise SystemExit("target molarity must be positive")
    if args.neutralizing_chloride != 12:
        raise SystemExit("this validated pVBTMA12 model requires exactly 12 neutralizing Cl- ions")

    system = pmd.load_file(args.prmtop, args.inpcrd)
    volume_ang3 = cell_volume_ang3(system.box)
    volume_l = volume_ang3 * ANGSTROM3_TO_LITER
    exact_pairs = args.target_molar * AVOGADRO * volume_l
    added_pairs = nearest_integer(exact_pairs)
    if added_pairs < 1:
        raise SystemExit("calculated added NaCl pair count is <1; inspect box construction")
    achieved_molar = added_pairs / (AVOGADRO * volume_l)

    water_names = {"WAT", "HOH", "TIP3", "TP3"}
    water_count = sum(1 for r in system.residues if r.name.upper() in water_names)

    result = {
        "target_added_nacl_molar": args.target_molar,
        "neutralizing_chloride_count": args.neutralizing_chloride,
        "neutralizing_ions_counted_toward_added_salt": False,
        "box_angstrom": [float(x) for x in system.box[:6]],
        "box_volume_angstrom3": volume_ang3,
        "box_volume_liter": volume_l,
        "water_residues_before_ion_replacement": water_count,
        "continuous_target_nacl_pairs": exact_pairs,
        "added_nacl_pairs": added_pairs,
        "expected_final_sodium_count": added_pairs,
        "expected_final_chloride_count": args.neutralizing_chloride + added_pairs,
        "achieved_nominal_added_nacl_molar": achieved_molar,
        "rounding_rule": "nearest integer, half up",
        "concentration_definition": "added NaCl pairs divided by initial periodic-cell volume; neutralizing Cl- excluded",
    }
    Path(args.json_out).write_text(json.dumps(result, indent=2) + "\n")

    leap = f"""# AUTO-GENERATED by prepare_salt_setup.py. Do not hand edit.\n# Added NaCl target: {args.target_molar:.6f} M\n# Actual initial box volume: {volume_ang3:.6f} A^3\n# Continuous pair count: {exact_pairs:.8f}\n# Added integer NaCl pairs: {added_pairs}\n# Achieved nominal added NaCl: {achieved_molar:.8f} M\nsource leaprc.gaff2\nsource leaprc.water.tip3p\nloadAmberParams frcmod.ionsjc_tip3p\nloadAmberParams ../05_forcefield_parameter_validation/pVBTMA12.frcmod\nPVB = loadMol2 ../04_charge_parameterization/pVBTMA12_gaff2_rct.mol2\nSYS = combine {{ PVB }}\nsolvateBox SYS TIP3PBOX 15.0\n# Stoichiometric resin counterions. These are separate from the bulk-salt target.\naddIonsRand SYS Cl- {args.neutralizing_chloride}\n# External NaCl pairs for the approximately 0.15 M condition.\naddIonsRand SYS Na+ {added_pairs} Cl- {added_pairs}\ncheck SYS\ncharge SYS\nsaveAmberParm SYS pVBTMA12_12Cl_015MNaCl_pilot.prmtop pVBTMA12_12Cl_015MNaCl_pilot.inpcrd\nsavePdb SYS pVBTMA12_12Cl_015MNaCl_pilot.pdb\nquit\n"""
    Path(args.leap_out).write_text(leap)

    print(f"box_volume_angstrom3: {volume_ang3:.6f}")
    print(f"continuous_target_nacl_pairs: {exact_pairs:.8f}")
    print(f"added_nacl_pairs: {added_pairs}")
    print(f"achieved_nominal_added_nacl_molar: {achieved_molar:.8f}")
    print(f"expected_final_Na: {added_pairs}")
    print(f"expected_final_Cl: {args.neutralizing_chloride + added_pairs}")


if __name__ == "__main__":
    main()
