source stage09_common.conf
source stage09_system.generated.conf
parmfile $stage09_prmtop
ambercoor $stage09_inpcrd
bincoordinates 02_equil_npt_500ps/equil500ps.coor
binvelocities 02_equil_npt_500ps/equil500ps.vel
extendedSystem 02_equil_npt_500ps/equil500ps.xsc
seed 202609193
langevin on
langevinTemp 310.15
langevinPiston on
langevinPistonTarget 1.01325
langevinPistonPeriod 100.0
langevinPistonDecay 50.0
langevinPistonTemp 310.15
useGroupPressure yes
DCDfile 03_acceptance_npt_1ns/acceptance1ns.dcd
DCDfreq 1000
outputName 03_acceptance_npt_1ns/acceptance1ns
run 500000
