amber             yes
parmfile          ../01_build_bulk/cl_aq.prmtop
ambercoor         ../01_build_bulk/cl_aq.inpcrd
binCoordinates    cl_aq_min.restart.coor

outputname        cl_aq_nvt_heat
binaryoutput      yes

exclude           scaled1-4
readexclusions    yes
1-4scaling        0.833333333
scnb              2.0

switching         off
cutoff            9.0
pairlistdist      11.0
LJcorrection      on
PME               yes
PMEGridSpacing    1.0

cellBasisVector1  44.146793 0.0 0.0
cellBasisVector2  0.0 43.771796 0.0
cellBasisVector3  0.0 0.0 44.318678
cellOrigin        0.0 0.0 0.0

temperature       310.15
rigidBonds        all
rigidTolerance    1.0e-8
timestep          2.0

langevin          on
langevinTemp      310.15
langevinDamping   1.0

outputEnergies    500
outputTiming      500
restartfreq       2500
dcdfreq           2500
xstFreq           2500

reinitvels         100.0
run                25000
reinitvels         200.0
run                25000
reinitvels         310.15
run                50000
