from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class OrcaSettings:
    functional: str = "wB97X-D3"
    basis: str = "def2-TZVPD"
    solvent: str = "Water"
    epsilon: float = 72.5
    temperature: float = 310.15
    maxcore: int = 4000
    nprocs: int = 32
    maxiter: int = 350


CALC_TYPES = [
    "GOAT global optimization (GFN2-xTB)",
    "r2SCAN-3c geometry optimization",
    "wB97X-D3 geometry optimization",
    "Frequency calculation",
    "EDA-NOCV analysis",
    "NBO analysis",
]


def _functional_keyword(settings: OrcaSettings) -> str:
    if settings.functional == "r2SCAN-3c":
        return "r2SCAN-3c"
    return f"{settings.functional} {settings.basis}"


def _pal_block(settings: OrcaSettings) -> str:
    return f"""%maxcore {settings.maxcore}

%pal
   nprocs {settings.nprocs}
end"""


def _cpcm_block(settings: OrcaSettings) -> str:
    return f"""%cpcm
   smd true
   SMDSolvent "{settings.solvent}"
   epsilon {settings.epsilon:g}
end"""


def _geom_block(settings: OrcaSettings) -> str:
    return f"""%geom
   MaxIter {settings.maxiter}
end"""


def _freq_block(settings: OrcaSettings) -> str:
    return f"""%freq
   TEMP {settings.temperature:g}
end"""


def xyzfile_line(charge: int, multiplicity: int, xyz_filename: str) -> str:
    return f"* xyzfile {charge} {multiplicity} {xyz_filename}"


def build_orca_input(
    *,
    title: str,
    calc_type: str,
    xyz_filename: str,
    charge: int,
    multiplicity: int,
    settings: OrcaSettings,
    pfas_atom_count: int | None = None,
    total_atom_count: int | None = None,
) -> str:
    header = f"# Generated by PFAS-Removal-DFT Streamlit GUI\n# {title}\n"
    if calc_type == "GOAT global optimization (GFN2-xTB)":
        return "\n".join(
            [
                header,
                f"! XTB GOAT ALPB({settings.solvent})",
                "",
                _pal_block(settings),
                "",
                xyzfile_line(charge, multiplicity, xyz_filename),
                "",
            ]
        )

    if calc_type == "r2SCAN-3c geometry optimization":
        keyword = "! r2SCAN-3c DefGrid3 TightOpt CPCM"
        return "\n".join(
            [
                header,
                keyword,
                "",
                _geom_block(settings),
                "",
                _pal_block(settings),
                "",
                _cpcm_block(settings),
                "",
                xyzfile_line(charge, multiplicity, xyz_filename),
                "",
            ]
        )

    if calc_type == "wB97X-D3 geometry optimization":
        keyword = f"! {settings.functional} {settings.basis} DefGrid3 TightOpt CPCM"
        return "\n".join(
            [
                header,
                keyword,
                "",
                _geom_block(settings),
                "",
                _pal_block(settings),
                "",
                _cpcm_block(settings),
                "",
                xyzfile_line(charge, multiplicity, xyz_filename),
                "",
            ]
        )

    if calc_type == "Frequency calculation":
        keyword = f"! {_functional_keyword(settings)} DefGrid3 Freq CPCM"
        return "\n".join(
            [
                header,
                keyword,
                "",
                _geom_block(settings),
                "",
                _freq_block(settings),
                "",
                _pal_block(settings),
                "",
                _cpcm_block(settings),
                "",
                xyzfile_line(charge, multiplicity, xyz_filename),
                "",
            ]
        )

    if calc_type == "EDA-NOCV analysis":
        if pfas_atom_count is None or total_atom_count is None or pfas_atom_count >= total_atom_count:
            raise ValueError("EDA input generation requires the total atom count and PFAS fragment atom count.")
        frag1_end = total_atom_count - pfas_atom_count - 1
        frag2_start = total_atom_count - pfas_atom_count
        keyword = f"! {_functional_keyword(settings)} TightSCF EDA CPCM"
        return "\n".join(
            [
                header,
                keyword,
                "",
                _pal_block(settings),
                "",
                _cpcm_block(settings),
                "",
                "%EDA",
                '  FRAG1_METHODFILE "frag1method.txt"',
                '  FRAG2_METHODFILE "frag2method.txt"',
                "  FRAG1_C 1",
                "  FRAG1_M 1",
                "  FRAG2_C -1",
                "  FRAG2_M 1",
                "end",
                "",
                xyzfile_line(charge, multiplicity, xyz_filename),
                "",
                "%frag",
                "  Definition",
                f"    1 {{0:{frag1_end}}} end",
                f"    2 {{{frag2_start}:{total_atom_count - 1}}} end",
                "  end",
                "end",
                "",
            ]
        )

    if calc_type == "NBO analysis":
        keyword = f"! {_functional_keyword(settings)} TightSCF CPCM"
        return "\n".join(
            [
                header,
                keyword,
                "",
                _pal_block(settings),
                "",
                _cpcm_block(settings),
                "",
                "%nbo",
                '  NBOKEYLIST = "$NBO NBO NPA CMO FNAO NBOSUM BNDIDX PLOT DIPOLE ARCHIVE PRINT=2 MEMORY=4GB $END"',
                "end",
                "",
                xyzfile_line(charge, multiplicity, xyz_filename),
                "",
            ]
        )

    raise ValueError(f"Unsupported calculation type: {calc_type}")
