source stage08_common.conf
source stage08_system.generated.conf

parmfile               $stage07_prmtop
ambercoor              $stage07_inpcrd
bincoordinates         04_equil_npt_500ps/equil500ps.coor
binvelocities          04_equil_npt_500ps/equil500ps.vel
extendedSystem         04_equil_npt_500ps/equil500ps.xsc

seed                   202609185
langevin               on
langevinTemp           310.15
langevinPiston         on
langevinPistonTarget   1.01325
langevinPistonPeriod   100.0
langevinPistonDecay    50.0
langevinPistonTemp     310.15
useGroupPressure       yes

# 2 ps trajectory resolution for end-effect/contact analysis.
DCDfile                05_acceptance_npt_1ns/acceptance1ns.dcd
DCDfreq                1000
outputName             05_acceptance_npt_1ns/acceptance1ns
run                    500000
