
source ../stage10_common.conf
parmfile ../inputs/pVBTMA12_PFOA_assoc.prmtop
ambercoor ../inputs/pVBTMA12_PFOA_assoc.inpcrd
bincoordinates 02_prod_1ns/prod_02.coor
binvelocities 02_prod_1ns/prod_02.vel
extendedSystem 02_prod_1ns/prod_02.xsc
firsttimestep 1250000
seed 202609323
langevin on
langevinTemp 310.15
langevinPiston on
langevinPistonTarget 1.01325
langevinPistonPeriod 100.0
langevinPistonDecay 50.0
langevinPistonTemp 310.15
useGroupPressure yes
DCDfile 03_prod_1ns/prod_03.dcd
DCDfreq 1000
outputName 03_prod_1ns/prod_03
run 500000
