python
from pymol import cmd
from pymol.cgo import BEGIN, LINES, TRIANGLES, ALPHA, LINEWIDTH, COLOR, VERTEX, END
cmd.reinitialize()
cmd.bg_color('white')
cmd.set('orthoscopic', 1)
cmd.set('ray_opaque_background', 0)
cmd.set('antialias', 2)
cmd.set('ray_shadows', 1)
cmd.set('connect_mode', 0)
cmd.set('stick_quality', 24)
cmd.set('sphere_quality', 2)
cmd.set('depth_cue', 0)
cmd.set('spec_reflect', .25)
cmd.set('ambient', .35)
cmd.set('direct', .65)
cmd.load('/mnt/d/work/rz_orca_pfasremoval/00-0b-Supplementary_Materials_staging/Supplementary_Materials/02_Figure_Plotting_and_Data/01_main_text_figures/Figure_14_MD_model_and_workflow/structure_renders/render_inputs/polymer.pdb', 'polymer_obj')
cmd.load('/mnt/d/work/rz_orca_pfasremoval/00-0b-Supplementary_Materials_staging/Supplementary_Materials/02_Figure_Plotting_and_Data/01_main_text_figures/Figure_14_MD_model_and_workflow/structure_renders/render_inputs/pfoa.pdb', 'pfoa')
cmd.load('/mnt/d/work/rz_orca_pfasremoval/00-0b-Supplementary_Materials_staging/Supplementary_Materials/02_Figure_Plotting_and_Data/01_main_text_figures/Figure_14_MD_model_and_workflow/structure_renders/render_inputs/water_local.pdb', 'water')
cmd.select('sodium', 'none')
cmd.load('/mnt/d/work/rz_orca_pfasremoval/00-0b-Supplementary_Materials_staging/Supplementary_Materials/02_Figure_Plotting_and_Data/01_main_text_figures/Figure_14_MD_model_and_workflow/structure_renders/render_inputs/chloride_local.pdb', 'chloride')
if len(cmd.get_model('polymer_obj').bond) < 385:
    raise RuntimeError('Polymer connectivity incomplete; inspect topology/CONECT records')
if len(cmd.get_model('pfoa').bond) < 24:
    raise RuntimeError('PFOA connectivity incomplete; inspect topology/CONECT records')
cmd.unbond('water and elem H', 'water and elem H')
cmd.unbond('water and elem O', 'water and elem O')
if len(cmd.get_model('water').bond) != 2 * cmd.count_atoms('water') // 3:
    raise RuntimeError('Water connectivity differs from two O-H bonds per molecule')

cmd.hide('everything')
cmd.remove('(polymer_obj or pfoa) and hydro')
for element, color in {'C': '#4d4d4d', 'N': '#354f9c', 'O': '#d62728', 'F': '#47b8a6', 'H': '#f2f2f2', 'S': '#e0b33f'}.items():
    cmd.set_color('atlas_' + element, [int(color[i:i+2],16)/255 for i in (1,3,5)])
    cmd.color('atlas_' + element, 'pfoa and elem ' + element)
for element in {'C': '#4d4d4d', 'N': '#354f9c', 'O': '#d62728', 'F': '#47b8a6', 'H': '#f2f2f2', 'S': '#e0b33f'}.keys():
    cmd.color('atlas_' + element, 'polymer_obj and elem ' + element)
cmd.set('sphere_scale', .25, 'polymer_obj')
cmd.set('stick_radius', .13, 'polymer_obj')
cmd.set('stick_transparency', .10, 'polymer_obj')
cmd.set('sphere_scale', .25, 'pfoa')
cmd.set('stick_radius', .13, 'pfoa')
cmd.show('sticks', 'pfoa')
cmd.show('spheres', 'pfoa')
cmd.show('spheres', 'sodium or chloride')
cmd.set('sphere_scale', .34, 'sodium or chloride')
cmd.set_color('ion_na', [.84,.56,.22])
cmd.set_color('ion_cl', [.39,.66,.33])
cmd.color('ion_na', 'sodium')
cmd.color('ion_cl', 'chloride')
cmd.show('sticks', 'polymer_obj')
cmd.show('spheres', 'polymer_obj')
cmd.show('sticks', 'water')
cmd.show('spheres', 'water')
cmd.set('sphere_scale', .075, 'water')
cmd.set('sphere_scale', .05, 'water and elem H')
cmd.set('stick_radius', .055, 'water')
cmd.set('stick_transparency', .34, 'water')
cmd.set('sphere_transparency', .40, 'water')
cmd.color('atlas_O', 'water and elem O')
cmd.color('atlas_H', 'water and elem H')
cmd.set_view((0.0016280642, 0.3488400578, -0.9371808767, -0.9964369535, 0.0795942843, 0.0278958008, 0.0843254104, 0.933796227, 0.3477267027, 0.0, 0.0, -63.473526, 24.5099048615, 35.6587181091, 20.001663208, 50.0430107117, 76.9040374756, 20.0))
cmd.png('/mnt/d/work/rz_orca_pfasremoval/00-0b-Supplementary_Materials_staging/Supplementary_Materials/02_Figure_Plotting_and_Data/01_main_text_figures/Figure_14_MD_model_and_workflow/structure_renders/figure14_hydrated_site.png', width=1800, height=1800, dpi=600, ray=1)
python end
