source ../stage10_common.conf
parmfile ../inputs/pVBTMA12_PFOA_assoc.prmtop
ambercoor ../inputs/pVBTMA12_PFOA_assoc.inpcrd
bincoordinates 09_prod_1ns/prod_09.coor
binvelocities 09_prod_1ns/prod_09.vel
extendedSystem 09_prod_1ns/prod_09.xsc
firsttimestep 4750000
seed 202609370
langevin on
langevinTemp 310.15
langevinPiston on
langevinPistonTarget 1.01325
langevinPistonPeriod 100.0
langevinPistonDecay 50.0
langevinPistonTemp 310.15
useGroupPressure yes
DCDfile 10_prod_1ns/prod_10.dcd
DCDfreq 1000
outputName 10_prod_1ns/prod_10
run 500000
